/**
 * AI-Generated Test Suite for isEmpty function
 *
 * Generated by: Claude (Anthropic) via Cursor IDE
 * Date: December 8, 2025
 *
 * This test suite was generated using AI assistance based on the test plan
 * from Phase 1 of the assignment. The AI was prompted to cover all planned
 * test cases plus identify additional edge cases that may have been missed.
 *
 * Oracle: The expected behavior is derived from:
 * 1. The function's JSDoc documentation
 * 2. Lodash isEmpty specification (as this is a lodash-based utility)
 * 3. JavaScript type coercion and emptiness semantics
 */

import isEmpty from "../../src/isEmpty.js";

describe("isEmpty - AI Generated Tests", () => {
  // ============================================================
  // TEST CASES FROM PHASE 1 TEST PLAN
  // These tests directly implement the planned test cases
  // ============================================================

  describe("Planned Test Cases from Phase 1", () => {
    // Test Case 1.1: null as input
    test("TC 1.1: Should return true when null is provided", () => {
      expect(isEmpty(null)).toBe(true);
    });

    // Test Case 1.2: boolean as input
    test("TC 1.2: Should return true when boolean (true) is provided", () => {
      expect(isEmpty(true)).toBe(true);
    });

    // Test Case 1.3: number as input
    test("TC 1.3: Should return true when number (1) is provided", () => {
      expect(isEmpty(1)).toBe(true);
    });

    // Test Case 1.4: string as input
    test("TC 1.4: Should return false when non-empty string 'abc' is provided", () => {
      expect(isEmpty("abc")).toBe(false);
    });

    // Test Case 1.5: object as input
    test("TC 1.5: Should return false when object { 'a': 1 } is provided", () => {
      expect(isEmpty({ a: 1 })).toBe(false);
    });

    // Test Case 1.6: list as input
    test("TC 1.6: Should return false when array [1, 2, 3] is provided", () => {
      expect(isEmpty([1, 2, 3])).toBe(false);
    });

    // Test Case 1.7: empty list as input (boundary)
    test("TC 1.7: Should return true when empty array [] is provided", () => {
      expect(isEmpty([])).toBe(true);
    });

    // Test Case 1.8: empty object as input (boundary)
    test("TC 1.8: Should return true when empty object {} is provided", () => {
      expect(isEmpty({})).toBe(true);
    });

    // Test Case 1.9: empty string as input (boundary)
    test("TC 1.9: Should return true when empty string '' is provided", () => {
      expect(isEmpty("")).toBe(true);
    });
  });

  // ============================================================
  // ADDITIONAL AI-IDENTIFIED EDGE CASES
  // These tests cover scenarios not explicitly in the Phase 1 plan
  // ============================================================

  describe("Additional Edge Cases - Null/Undefined", () => {
    test("Should return true when undefined is provided", () => {
      expect(isEmpty(undefined)).toBe(true);
    });

    test("Should return true when void 0 (undefined) is provided", () => {
      expect(isEmpty(void 0)).toBe(true);
    });
  });

  describe("Additional Edge Cases - Boolean Values", () => {
    test("Should return true when false is provided", () => {
      expect(isEmpty(false)).toBe(true);
    });

    test("Should return true when Boolean object (true) is provided", () => {
      // Boolean objects are objects, not primitives
      expect(isEmpty(new Boolean(true))).toBe(true);
    });

    test("Should return true when Boolean object (false) is provided", () => {
      expect(isEmpty(new Boolean(false))).toBe(true);
    });
  });

  describe("Additional Edge Cases - Number Values", () => {
    test("Should return true when 0 is provided", () => {
      expect(isEmpty(0)).toBe(true);
    });

    test("Should return true when -0 is provided", () => {
      expect(isEmpty(-0)).toBe(true);
    });

    test("Should return true when negative number is provided", () => {
      expect(isEmpty(-42)).toBe(true);
    });

    test("Should return true when NaN is provided", () => {
      expect(isEmpty(NaN)).toBe(true);
    });

    test("Should return true when Infinity is provided", () => {
      expect(isEmpty(Infinity)).toBe(true);
    });

    test("Should return true when -Infinity is provided", () => {
      expect(isEmpty(-Infinity)).toBe(true);
    });

    test("Should return true when Number.MAX_VALUE is provided", () => {
      expect(isEmpty(Number.MAX_VALUE)).toBe(true);
    });

    test("Should return true when Number.MIN_VALUE is provided", () => {
      expect(isEmpty(Number.MIN_VALUE)).toBe(true);
    });
  });

  describe("Additional Edge Cases - String Values", () => {
    test("Should return false when single character string is provided", () => {
      expect(isEmpty("a")).toBe(false);
    });

    test("Should return false when whitespace-only string is provided", () => {
      // Whitespace is still characters, so not empty
      expect(isEmpty("   ")).toBe(false);
    });

    test("Should return false when string with newlines is provided", () => {
      expect(isEmpty("\n\t")).toBe(false);
    });

    test("Should return false when unicode string is provided", () => {
      expect(isEmpty("日本語")).toBe(false);
    });

    test("Should return false when emoji string is provided", () => {
      expect(isEmpty("🎉")).toBe(false);
    });

    test("Should return true when String object with empty value is provided", () => {
      expect(isEmpty(new String(""))).toBe(true);
    });

    test("Should return false when String object with value is provided", () => {
      expect(isEmpty(new String("hello"))).toBe(false);
    });
  });

  describe("Additional Edge Cases - Array Values", () => {
    test("Should return false when array with single element is provided", () => {
      expect(isEmpty([1])).toBe(false);
    });

    test("Should return false when array with null element is provided", () => {
      expect(isEmpty([null])).toBe(false);
    });

    test("Should return false when array with undefined element is provided", () => {
      expect(isEmpty([undefined])).toBe(false);
    });

    test("Should return false when nested empty array is provided", () => {
      // The outer array contains one element (the inner array)
      expect(isEmpty([[]])).toBe(false);
    });

    test("Should return false when sparse array with holes is provided", () => {
      // Array with holes still has length > 0
      const sparseArray = new Array(3);
      expect(isEmpty(sparseArray)).toBe(false);
    });

    test("Should return false when large array is provided", () => {
      const largeArray = new Array(1000).fill(0);
      expect(isEmpty(largeArray)).toBe(false);
    });
  });

  describe("Additional Edge Cases - Object Values", () => {
    test("Should return false when object with multiple properties is provided", () => {
      expect(isEmpty({ a: 1, b: 2, c: 3 })).toBe(false);
    });

    test("Should return false when nested object is provided", () => {
      expect(isEmpty({ nested: { value: 1 } })).toBe(false);
    });

    test("Should return false when object with null value is provided", () => {
      expect(isEmpty({ key: null })).toBe(false);
    });

    test("Should return false when object with undefined value is provided", () => {
      expect(isEmpty({ key: undefined })).toBe(false);
    });

    test("Should return true when object created with Object.create(null) is empty", () => {
      const nullProtoObj = Object.create(null);
      expect(isEmpty(nullProtoObj)).toBe(true);
    });

    test("Should return false when object created with Object.create(null) has properties", () => {
      const nullProtoObj = Object.create(null);
      nullProtoObj.key = "value";
      expect(isEmpty(nullProtoObj)).toBe(false);
    });

    test("Should return true when object has only inherited properties", () => {
      const parent = { inherited: true };
      const child = Object.create(parent);
      // child has no own properties, only inherited
      expect(isEmpty(child)).toBe(true);
    });

    test("Should return true when prototype object is provided", () => {
      expect(isEmpty(Object.prototype)).toBe(true);
    });
  });

  describe("Additional Edge Cases - Map and Set", () => {
    test("Should return true when empty Map is provided", () => {
      expect(isEmpty(new Map())).toBe(true);
    });

    test("Should return false when non-empty Map is provided", () => {
      const map = new Map();
      map.set("key", "value");
      expect(isEmpty(map)).toBe(false);
    });

    test("Should return false when Map with multiple entries is provided", () => {
      const map = new Map([
        ["a", 1],
        ["b", 2],
      ]);
      expect(isEmpty(map)).toBe(false);
    });

    test("Should return true when empty Set is provided", () => {
      expect(isEmpty(new Set())).toBe(true);
    });

    test("Should return false when non-empty Set is provided", () => {
      const set = new Set([1, 2, 3]);
      expect(isEmpty(set)).toBe(false);
    });

    test("Should return false when Set with single element is provided", () => {
      expect(isEmpty(new Set([1]))).toBe(false);
    });
  });

  describe("Additional Edge Cases - Functions", () => {
    test("Should return true when function is provided", () => {
      expect(isEmpty(function () {})).toBe(true);
    });

    test("Should return true when arrow function is provided", () => {
      expect(isEmpty(() => {})).toBe(true);
    });

    test("Should return true when async function is provided", () => {
      expect(isEmpty(async function () {})).toBe(true);
    });

    test("Should return true when generator function is provided", () => {
      expect(isEmpty(function* () {})).toBe(true);
    });

    test("Should return true when class is provided", () => {
      expect(isEmpty(class MyClass {})).toBe(true);
    });
  });

  describe("Additional Edge Cases - TypedArrays", () => {
    test("Should return true when empty Uint8Array is provided", () => {
      expect(isEmpty(new Uint8Array())).toBe(true);
    });

    test("Should return false when non-empty Uint8Array is provided", () => {
      expect(isEmpty(new Uint8Array([1, 2, 3]))).toBe(false);
    });

    test("Should return true when empty Int32Array is provided", () => {
      expect(isEmpty(new Int32Array())).toBe(true);
    });

    test("Should return false when non-empty Float64Array is provided", () => {
      expect(isEmpty(new Float64Array([1.5, 2.5]))).toBe(false);
    });

    test("Should return true when empty ArrayBuffer view is provided", () => {
      expect(isEmpty(new Uint8Array(new ArrayBuffer(0)))).toBe(true);
    });
  });

  describe("Additional Edge Cases - Special Objects", () => {
    test("Should return true when Date object is provided", () => {
      // Date objects have no own enumerable properties
      expect(isEmpty(new Date())).toBe(true);
    });

    test("Should return true when RegExp object is provided", () => {
      // RegExp objects have no own enumerable properties by default
      expect(isEmpty(/test/)).toBe(true);
    });

    test("Should return true when Error object is provided", () => {
      // Error objects have no own enumerable properties by default
      expect(isEmpty(new Error("test"))).toBe(true);
    });

    test("Should return true when Symbol is provided", () => {
      expect(isEmpty(Symbol("test"))).toBe(true);
    });
  });

  describe("Additional Edge Cases - Arguments Object", () => {
    test("Should return true when empty arguments object is provided", () => {
      function testFunc() {
        return isEmpty(arguments);
      }
      expect(testFunc()).toBe(true);
    });

    test("Should return false when non-empty arguments object is provided", () => {
      function testFunc() {
        return isEmpty(arguments);
      }
      expect(testFunc(1, 2, 3)).toBe(false);
    });
  });

  // ============================================================
  // E-COMMERCE CONTEXT TESTS
  // Tests relevant to the e-commerce application scenarios
  // ============================================================

  describe("E-Commerce Context Tests", () => {
    test("Should correctly identify empty shopping cart (empty array)", () => {
      const shoppingCart = [];
      expect(isEmpty(shoppingCart)).toBe(true);
    });

    test("Should correctly identify non-empty shopping cart", () => {
      const shoppingCart = [
        { productId: "123", quantity: 2, price: 29.99 },
      ];
      expect(isEmpty(shoppingCart)).toBe(false);
    });

    test("Should correctly identify empty search results", () => {
      const searchResults = [];
      expect(isEmpty(searchResults)).toBe(true);
    });

    test("Should correctly identify empty product filters", () => {
      const filters = {};
      expect(isEmpty(filters)).toBe(true);
    });

    test("Should correctly identify applied product filters", () => {
      const filters = { category: "electronics", minPrice: 100 };
      expect(isEmpty(filters)).toBe(false);
    });

    test("Should correctly identify empty user form data", () => {
      const formData = {};
      expect(isEmpty(formData)).toBe(true);
    });

    test("Should correctly identify filled user form data", () => {
      const formData = {
        name: "John Doe",
        email: "john@example.com",
      };
      expect(isEmpty(formData)).toBe(false);
    });

    test("Should correctly identify empty producer product list", () => {
      const producerProducts = [];
      expect(isEmpty(producerProducts)).toBe(true);
    });
  });
});
